### PR TITLE
Get numeral from npm instead of Bower

### PR DESCRIPTION
**Pull request by josemarluedke**
This drops the bower dependency and use numeral from npm instead.

It also uses Ember CLI feature to import amd modules when it is available.

### CODE REVIEW

**Comment by jayphelps** [comment]
Hey @josemarluedke would you be interested in having this project transferred to you as the new maintainer? I no longer use Ember, so I can't be confident of any proposed changes and hate to have things sit abandoned.

**Comment by jayphelps** [comment]
FWIW I also think this package should be renamed ember-numeral (npm package is also available)

https://twitter.com/_jayphelps/status/582699724983037953

I'm happy to transfer the existing npm package name to you and help deprecate the ember-cli-numeral package in favor of `ember-numeral`.

---

It's been a little while since I was active in the community so people's opinions on the naming conventions may have changed. I'll defer to your judgment.

**Comment by josemarluedke** [comment]
@jayphelps I would be happy to maintain the project. I also agree with using `ember-numeral`.

**Comment by jayphelps** [comment]
@josemarluedke cool. to transfer, you'll need to delete your Github fork of this project. lmk when you've done that.

image

**Comment by josemarluedke** [comment]
@jayphelps deleted. It should be ok to transfer now.

**Comment by jayphelps** [comment]
I've initiated transfer and also given you owner permission to the [npm package](https://www.npmjs.com/package/ember-cli-numeral). Lmk if there is anything else I am missing! 🎉

**Comment by josemarluedke** [comment]
Awesome! Thank you @jayphelps.

**Comment by jayphelps** [comment]
You're welcome. Thanks for taking this over. The only thing I ask is that my original copyright not be removed--of course you can add yourself as well.

**Pull request merged**
